name: Deploy to GitHub Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22 # Kita naikkan ke versi terbaru

      - name: Setup pnpm
        uses: pnpm/action-setup@v4 # Update ke v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build project
        # Menggunakan --filter untuk menjalankan build hanya di folder kimia-app
        run: pnpm --filter @workspace/kimia-app exec vite build --base=/chemigo-app/

      - name: Fix SPA Router
        run: cp artifacts/kimia-app/dist/index.html artifacts/kimia-app/dist/404.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './artifacts/kimia-app/dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
